# Generated by Django 5.0.3 on 2024-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_mgroup_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgroup',
            name='category',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=20),
        ),
    ]
