# Generated by Django 5.0.3 on 2024-03-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
    ]
